# Generated by Django 5.1.3 on 2024-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaiverity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
